// <auto-generated />
using System;
using API_testing2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_testing2.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_testing2.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fee")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SizeMeters")
                        .HasColumnType("int");

                    b.Property<int?>("Tenants")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2023, 8, 16, 15, 51, 29, 909, DateTimeKind.Local).AddTicks(7734),
                            Details = "La villa grande",
                            Fee = 86m,
                            ImageUrl = "",
                            Name = "Villa número 1",
                            SizeMeters = 32,
                            Tenants = 10,
                            Update = new DateTime(2023, 8, 16, 15, 51, 29, 909, DateTimeKind.Local).AddTicks(7745)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2023, 8, 16, 15, 51, 29, 909, DateTimeKind.Local).AddTicks(7747),
                            Details = "La villa mediana",
                            Fee = 50m,
                            ImageUrl = "",
                            Name = "Villa número 2",
                            SizeMeters = 25,
                            Tenants = 7,
                            Update = new DateTime(2023, 8, 16, 15, 51, 29, 909, DateTimeKind.Local).AddTicks(7748)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2023, 8, 16, 15, 51, 29, 909, DateTimeKind.Local).AddTicks(7750),
                            Details = "La villa pequeña",
                            Fee = 28m,
                            ImageUrl = "",
                            Name = "Villa número 3",
                            SizeMeters = 18,
                            Tenants = 2,
                            Update = new DateTime(2023, 8, 16, 15, 51, 29, 909, DateTimeKind.Local).AddTicks(7750)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
